In [1]:
a=([10,20,30,40,50])
a

[10, 20, 30, 40, 50]

In [2]:
a=([10,20,30])
b=([30,40,50])
a
b

[30, 40, 50]

In [3]:
a=([10,20,30])
b=([30,40,50])
print(a)
b

[10, 20, 30]


[30, 40, 50]

In [4]:
import numpy as np
data=np.array(a)
data

array([10, 20, 30])

In [5]:
h=np.mean(data)
h

np.float64(20.0)

In [9]:
print(np.max(b))
    

50


In [10]:
print(np.min(a))

10


In [11]:
f=np.zeros([5,6])
f

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [13]:
f=np.ones([5,6])
f

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [15]:
f=np.ones([3,3])
f

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
n=np.random.rand(8,7)
n

array([[0.09373395, 0.93028063, 0.36786322, 0.8297007 , 0.01734297,
        0.76807204, 0.92839924],
       [0.27992747, 0.31336564, 0.87790464, 0.57614003, 0.06959162,
        0.52545149, 0.87403271],
       [0.58729322, 0.17281062, 0.25122474, 0.1980827 , 0.41305039,
        0.64516471, 0.53802937],
       [0.25883215, 0.15143407, 0.90322937, 0.08033545, 0.74748193,
        0.38922394, 0.82681183],
       [0.45689294, 0.59530832, 0.79265999, 0.26866647, 0.53887107,
        0.188402  , 0.72771443],
       [0.79127042, 0.04100608, 0.01748295, 0.17907947, 0.48948215,
        0.22944676, 0.79116235],
       [0.32146598, 0.31357527, 0.58502958, 0.1278063 , 0.62978393,
        0.97349633, 0.00924628],
       [0.21563681, 0.07899456, 0.96227744, 0.97622945, 0.60326525,
        0.74460693, 0.87603428]])

In [17]:
n=np.random.rand(4,3)
n

array([[0.80927692, 0.09222858, 0.86383233],
       [0.92143519, 0.84172875, 0.51962855],
       [0.90023176, 0.60529995, 0.66840291],
       [0.40035038, 0.17723084, 0.72458149]])

In [20]:
saro=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
v=np.reshape(saro,(2,8))
v

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [24]:
m=np.arange(15).reshape(3,5)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [25]:
c=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
q=c[3:6]
q

array([4, 5, 6])

In [26]:
c=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
q=c[3:10]
q

array([ 4,  5,  6,  7,  8,  9, 10])

In [27]:
c=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
q=c[0:15]
q

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [28]:
a=np.array([10,20,30])
b=np.array([1,2,3])
a+b

array([11, 22, 33])

In [29]:
a=np.array([10,20,30])
b=np.array([1,2,3])
a-b

array([ 9, 18, 27])

In [30]:
a=np.array([10,20,30])
b=np.array([1,2,3])
a*b

array([10, 40, 90])

In [31]:
a=np.array([10,20,30])
b=np.array([1,2,3])
a%b

array([0, 0, 0])

In [32]:
a=np.array([10,20,30])
b=np.array([1,2,3])
a**b

array([   10,   400, 27000])

In [35]:
a=np.array([[1,2,3],[6,7,8]])
b=np.array([[4,5],
            [8,4],
            [6,5]])
c=np.dot(a,b)
c

array([[ 38,  28],
       [128,  98]])

In [39]:
SARO=np.array([[1,2,3],[4,5,6]])
print(SARO.T)


[[1 4]
 [2 5]
 [3 6]]


In [40]:
arr=np.array([5,2,5,8,11,16,1,21,9])
print(np.sort(arr))

[ 1  2  5  5  8  9 11 16 21]


In [42]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.concatenate((a,b)))

[1 2 3 4 5 6]


In [45]:
arr=np.array([1,2,3,4,5,77,66,66,7,1,23])
d=np.unique(arr)
d

array([ 1,  2,  3,  4,  5,  7, 23, 66, 77])

In [46]:
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [47]:
print(np.eye(6))

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [48]:
j=np.linspace(0,10,7)
print(j)

[ 0.          1.66666667  3.33333333  5.          6.66666667  8.33333333
 10.        ]
