In [3]:
a="saravanan"
a

'saravanan'

In [4]:
import numpy as np

In [5]:
zeros=np.zeros(7)
print(zeros)

[0. 0. 0. 0. 0. 0. 0.]


In [6]:
one=np.ones(5)
one

array([1., 1., 1., 1., 1.])

In [9]:
a=np.arange(1,20)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [12]:
a=np.arange(1,10,2)
print(a)

[1 3 5 7 9]


In [16]:
a=np.arange(2,10,2)
print(a)

[2 4 6 8]


In [18]:
a=np.random.rand(10)
a

array([0.90202328, 0.49708325, 0.40057706, 0.02899562, 0.22190193,
       0.52858569, 0.59428187, 0.64416358, 0.07288325, 0.54100864])

In [19]:
arr=np.arange(1,101)

In [20]:
print("array:",arr)

array: [  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [22]:
print("ndim:",arr.ndim)

ndim: 1


In [23]:
print("shape:",arr.shape)

shape: (100,)


In [25]:
print("size:",arr.size)

size: 100


In [26]:
print("dtype:",arr.dtype)

dtype: int32


In [27]:
print("itemsize:",arr.itemsize)

itemsize: 4


In [28]:
print("nbytes:",arr.nbytes)

nbytes: 400


In [29]:
a=np.array([4.1,5.8,2.8,2.0,6.7])

In [31]:
print(a.astype(np.float32))

[4.1 5.8 2.8 2.  6.7]


In [32]:
print(a.astype(np.float64))

[4.1 5.8 2.8 2.  6.7]


In [33]:
print(a.astype(np.int32))

[4 5 2 2 6]


In [42]:
np.random.seed(42)
data=np.random.randint(10,101,(8,5))
print(data)



[[ 61  24  81  70  30]
 [ 92  96  84  84  97]
 [ 33  12  31  62  11]
 [ 97  39  47  11  73]
 [ 69  30  42  85  67]
 [ 31  98  58 100  68]
 [ 51  69  89  24  71]
 [ 71  56  71  60  64]]


In [44]:
print(data.shape)

(8, 5)


In [45]:
print(data.dtype)

int32


In [48]:
a=np.arange(0,1,0.1)
a

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [51]:
b=np.linspace(0,1,100)
b

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [52]:
a=np.arange(1,37).reshape(6,6)
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [53]:
np.diag(a)

array([ 1,  8, 15, 22, 29, 36])

In [56]:
b=np.fliplr(a)
np.diag(b)

array([ 6, 11, 16, 21, 26, 31])

In [57]:
s=a[2:4,2:4]
s

array([[15, 16],
       [21, 22]])

In [58]:
a=np.arange(1,49).reshape(2,4,6)
a

array([[[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35, 36],
        [37, 38, 39, 40, 41, 42],
        [43, 44, 45, 46, 47, 48]]])

In [59]:
print("feature slice:")
print(a[:,:,0])

feature slice:
[[ 1  7 13 19]
 [25 31 37 43]]


In [62]:
print("ones:")
print(a[1,0,])

ones:
[25 26 27 28 29 30]
